const territoriesData = [

    {
        title: "Тереторія біля фермерського магазина",
        image: "https://i.postimg.cc/76tMpn4p/image-(11).webp",
        owner: "XxsSashaxxjj",
        startDate: "04.10.2026",
        endDate: "10.10.2026",
        status: "Зайнята",
    },
    {
        title: "Тереторія біля фермерського магазина",
        image: "https://i.postimg.cc/d1h4Qx4z/image-(12).webp",
        owner: "XxsSashaxxjj",
        startDate: "04.10.2026",
        endDate: "10.10.2026",
        status: "Зайнята",
    },
    {
        title: "Тереторія біля фермерського магазина",
        image: "https://i.postimg.cc/jSRcn5Mz/image-(13).webp",
        owner: "XxsSashaxxjj",
        startDate: "04.10.2026",
        endDate: "10.10.2026",
        status: "Зайнята",
    },
    {
        title: "Тереторія біля фермерського магазина",
        image: "https://i.postimg.cc/0QK01Jyh/image-(14).webp",
        owner: "-",
        startDate: "",
        endDate: "",
        status: "Вільна",
    },
    {
        title: "Тереторія біля автобусної компанії",
        image: "https://i.postimg.cc/prY8PQbg/image-(15).webp",
        owner: "-",
        startDate: "",
        endDate: "",
        status: "Вільна",
    },
    {
        title: "Тереторія біля автобусної компанії",
        image: "https://i.postimg.cc/JhDksCCj/image-(16).webp",
        owner: "-",
        startDate: "",
        endDate: "",
        status: "Вільна",
    },   
    {
        title: "Тереторія біля автотюнінга",
        image: "https://i.postimg.cc/yxPJMV0Y/image-(17).webp",
        owner: "Matviy105012",
        startDate: "04.10.2026",
        endDate: "10.10.2026",
        status: "Зайнята",
    },  
    {
        title: "Тереторія біля автотюнінга",
        image: "https://i.postimg.cc/PqWd3SWk/image-(18).webp",
        owner: "-",
        startDate: "",
        endDate: "",
        status: "Вільна",
    },    
    {
        title: "Тереторія біля автотюнінга",
        image: "https://i.postimg.cc/NfZYQ3bt/image-(19).webp",
        owner: "-",
        startDate: "",
        endDate: "",
        status: "Вільна",
    }, 
    {
        title: "Тереторія біля другого кільця",
        image: "https://i.postimg.cc/dVMMb8Qb/image-(20).webp",
        owner: "XxsSashaxxjj",
        startDate: "04.10.2026",
        endDate: "10.10.2026",
        status: "Зайнята",
    }, 
    {
        title: "Тереторія біля HARS",
        image: "https://i.postimg.cc/6qGjcmZF/image-(21).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    },  
     {
        title: "Тереторія біля HARS",
        image: "https://i.postimg.cc/6p0XC8tT/image-(22).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    },      
    {
        title: "Тереторія біля автотюнінга",
        image: "https://i.postimg.cc/66vxYjt0/image-(23).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    },
    {
        title: "Тереторія біля автосалону",
        image: "https://i.postimg.cc/3Ng67qw4/image-(24).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    }, 
    {
        title: "Тереторія біля автосалону",
        image: "https://i.postimg.cc/D0KjCcPC/image-(25).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    },     
    {
        title: "Тереторія біля автосалону",
        image: "https://i.postimg.cc/pXCGZzh4/image-(26).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    },     
    {
        title: "Тереторія біля автосалону",
        image: "https://i.postimg.cc/K8dnr8N5/image-(27).webp",
        owner: "KILLER_00803", 
        startDate: "04.10.2026",
        endDate: "10.10.2026",
        status: "Зайнята",
    },  
    {
        title: "Тереторія біля парка",
        image: "https://i.postimg.cc/MKgcgrQG/image-(28).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    }, 
    {
        title: "Тереторія біля заправки Арес",
        image: "https://i.postimg.cc/B6Zt2rdc/image-(29).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    }, 
    {
        title: "Тереторія біля заправки Арес",
        image: "https://i.postimg.cc/RhyF5NqP/image-(30).webp",
        owner: "-", 
        startDate: "",
        endDate: "",
        status: "Вільна",
    }, 
];